version: "3.8"
services:
  devcontainer:
    build: .
    ports:
      - 8081:8081
    volumes:
      - ./../:/workspaces/pump
      - pump-bashhistory:/root/commandhistory:cached
      # Forward docker socket to allow docker commands to be run from within the container
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
      - .env.local
    command: sleep infinity
  backend:
    build:
      context: ./../backend
      dockerfile: dev.Dockerfile
    restart: always
    environment:
      - DB_USER=dev
      - DB_PASSWORD=devpassword
      - DB=pump
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - 8080:8080
      - 4040:4040
    volumes:
      - ./../backend:/server/code
  db:
    build:
      context: ./../db
      dockerfile: dev.Dockerfile
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=devpassword
      - POSTGRES_DB=pump
    volumes:
      - ./../db/data:/var/lib/postgresql/data
volumes:
  pump-bashhistory:
