version: "3.8"
services:
  devcontainer:
    build: .
    ports:
      - 8081:8081
    volumes:
      - ./../:/workspaces/pump:cached
      - pump-bashhistory:/root/commandhistory:cached
      # Forward docker socket to allow docker commands to be run from within the container
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env.local
    command: sleep infinity
  backend:
    build:
      context: ./../backend
      dockerfile: dev.Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./../backend:/app:cached
volumes:
  pump-bashhistory:
